export const GET_ARTICLE_PENDING = "GET_ARTICLE_PENDING";
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_ERROR = "GET_ARTICLE_ERROR";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
